
disable_system_gems
disable_rubygems
bundle_path ".gems/bundler_gems"

gem "appengine-rack"
gem "dm-appengine"
gem "dm-ar-finders"
gem "sinatra"

gem "facets"
gem "json_pure"
gem "nayutaya-pure-nkf"
